management.endpoints.web.exposure.include=prometheus
management.metrics.tags.application=monitorable-application
#management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.slo.http.server.requests=50ms, 100ms, 150ms, 200ms, 300ms, 400ms, 500ms, 600ms, 700ms, 800ms, 900ms, 1000ms, 1200ms, 1500ms, 2000ms, 5000ms